debug: false
only-ascii: true
only-survival: true

chat:
  prefix: '[RS] '

feature:
  transaction: true
  servershop: true

interfaces:
  command:
    add: true
    buy: true
    detail: true
    equip: true
    list: true
    name: true
    result: true
    search: true
    sell: true
    set: true
    warp: true
  sign:
    equip: true

converter:
  chestshop: false
