name: RegionShop
main: com.geNAZt.RegionShop.RegionShopPlugin
database: true
description: A Shop which uses Regions as Shop Basement
version: 1.1.0b7
softdepend: [Vault, WorldGuard, WorldEdit]
commands:
    shop:
       description: RegionShops - Use the WorldGuard Regions as Shopping ground.
       usage: /shop
       permission: rs.use
       permission-message: You don't have Permissions to use the RegionShop
    convert:
       description: RegionShops - Use the WorldGuard Regions as Shopping ground.
       usage: /convert
       permission: rs.convert
       permission-message: You don't have Permissions to convert to RegionShop

permissions:
  rs.use:
    description: Wildcard permission set for RegionShop
    children:
      rs.help: true
      rs.list: true
      rs.warp: true
      rs.detail: true
      rs.stock.add: true
      rs.stock.set: true
      rs.stock.remove: true
      rs.stock.equip: true
      rs.detail: true
      rs.search: true
      rs.sell: true
      rs.buy: true
      rs.transaction: true
      rs.server.list: true
      rs.server.buy: true
      rs.server.sell: true
  rs.help:
    description: Permission for /shop help
    default: true
  rs.list:
    description: Explore the shop catalogue
    default: true
  rs.warp:
    description: Allows the usage of the warp command
    default: true
  rs.detail:
    description: Get more information based on a shop item id
    default: true
  rs.stock.add:
    description: Add item in hand to your shop stock
    default: true
  rs.stock.set:
    description: Adjust the price or the amount of a specific shop item id
    default: true
  rs.stock.remove:
    description: Remove a specific shop item id out of your shop catalogue
    default: true
  rs.stock.equip:
    description: Toggle the quick equip mode
    default: true
  rs.detail:
    description: Get additional informations about an shop item
    default: true
  rs.search:
    description: Search for a specific item on the whole marketplace 
    default: true
  rs.sell:
    description: Allows to sell Items to a Shop
    default: true
  rs.sell:
    description: Allows to buy Items from a Shop
    default: true
  rs.name:
    description: Allows you to change the name of a Shop
    default: false
  rs.transaction:
    description: Lets you see the Transaction Log
    default: true
  rs.admin:
    description: Administration of the Shops
    default: false
  rs.admin.reload:
    description: Reload the RegionShop Config
    default: false
  rs.server.sell:
    description: Sell to the Servershop
    default: true
  rs.server.buy:
    description: Buy things from the Servershop
    default: true
  rs.server.list:
    description: List all items inside the Servershop
    default: true