name: RegionShop
main: com.geNAZt.RegionShop.RegionShopPlugin
database: true
description: A Shop which uses Regions as Shop Basement
version: 0.1.0
commands:
    shop:
       description: RegionShops - Use the WorldGuard Regions as Shopping ground.
       usage: /shop
       permission: regionshop.use
       permission-message: You don't have Permissions to use the RegionShop